name: build
on:
  push:
    branches:
      - main
permissions:
  checks: write

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: httpYac API Tests
          path: report.xml
          reporter: java-junit
